version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: /server
    schedule:
      interval: monthly
    # TODO: https://github.com/dependabot/dependabot-core/issues/4009
    # versioning-strategy: "increase-if-necessary"
