version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: monthly
    groups:
      vite-svelte:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "vite"
          - "@sveltejs/vite-plugin-svelte*"
          - "svelte"
          - "eslint-plugin-svelte"
          - "prettier-plugin-svelte"
      npm-bump:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: cargo
    directory: /server
    schedule:
      interval: monthly
    groups:
      cargo-bump:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
    # TODO: https://github.com/dependabot/dependabot-core/issues/4009
    # versioning-strategy: "increase-if-necessary"
