on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "client/**"
      - ".github/workflows/client.yml"
name: client
env:
  NODE_VERSION: 22
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/client
        with:
          script: "lint"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/client
